### PR TITLE
Update to .NET 4.6.1 and remove unused usings

### PR DESCRIPTION
**Pull request by JamieMagee**
By upgrading from .NET 4.5.2 to .NET 4.6.1 you get a small perf bump from the runtime, and only exclude Vista (See [here](https://msdn.microsoft.com/en-us/library/8z6watww%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396) for supported .NET versions on Windows). There's approximately 10% lower RAM usage on my system.

Also, removing unused usings is just tidying more than anything else.

### CODE REVIEW

**Comment by DjScribbles** [comment]
I'm wrestling with the idea of abandoning Vista users on this one. [They are only 0.4% of Steam users](http://store.steampowered.com/hwsurvey?platform=pc), but I don't know if it's worth the abandonment for a small performance/ram bump in a primarily I/O bound application.

Thoughts?

**Comment by JamieMagee** [comment]
I think that if you're not supporting Windows XP, which makes up 2.5% of steam users, then you can afford to drop support for Vista users.

As for I/O performance, it wasn't something that I tested, but it would be interesting to see if there is any effect.

**Comment by DjScribbles** [comment]
I took the liberty of gathering some annecdotal performance info with Game Pipe, using Terraria (many small files) and The Witcher 2 (very large files). Overall, there doesn't seem to be any significant change:
Terraria moves are in pairs, moving between the same two drives. I did a couple trials of each with the hope of ensuring relatively fair caching treatment.

Running on .net 4.5.2:
Completed local move of Terraria. Transferring 9271 files, 99.1MB total, in 00:00:45.2892226 (averaging 2.2MB/sec).
Completed local move of Terraria. Transferring 9271 files, 99.1MB total, in 00:00:32.5623932 (averaging 3MB/sec).
Completed local move of Terraria. Transferring 9271 files, 99.1MB total, in 00:00:28.9813695 (averaging 3.4MB/sec).
Completed local move of Terraria. Transferring 9271 files, 99.1MB total, in 00:00:29.8550453 (averaging 3.3MB/sec).
Completed local move of The Witcher 2: Assassins of Kings Enhanced Edition. Transferring 1694 files, 18.5GB total, in 00:06:08.1061435 (averaging 51.4MB/sec).

Running on 4.6.1:
Completed local move of Terraria. Transferring 9271 files, 99.1MB total, in 00:01:11.9645776 (averaging 1.4MB/sec).
Completed local move of Terraria. Transferring 9271 files, 99.1MB total, in 00:00:29.5175253 (averaging 3.4MB/sec).
Completed local move of Terraria. Transferring 9271 files, 99.1MB total, in 00:00:28.6515494 (averaging 3.5MB/sec).
Completed local move of Terraria. Transferring 9271 files, 99.1MB total, in 00:00:30.1962866 (averaging 3.3MB/sec).
Completed local move of The Witcher 2: Assassins of Kings Enhanced Edition. Transferring 1694 files, 18.5GB total, in 00:06:09.3032762 (averaging 51.3MB/sec).

**Comment by JamieMagee** [comment]
Okay, so negligible I/O benefit and 10% performance bump otherwise, versus dropping support for the 0.4% of steam users running vista.

Personally I think that the tradeoff is worth it, but it's up to you. If you want to go ahead I'll rebase the pull request on top of master so you can merge it in.

**Comment by DjScribbles** [comment]
I've already done the merge locally, I've just been waiting to push until I decide for sure, although I'm leaning towards staying on 1.5.2 (while folding in the other changes).

**Pull request merged**
